const blackPower = [
    "Understanding racial segregation in the united states", 
    "American Black Film Festival",
    "Cop Block",
    "HuffPost Black Voices", 
    "Pan-Africanism", 
    "Black Panther Party", 
    "Black panther", 
    "Black (Color)"
];
const antiMuslim = [];
const whiteNationalist = [
    "Fly the American Flag",
    "America the Beautiful",
    "American Patriots",
    "I Love the USA",
    "Proud to be an American",
    "Patriot Nation",
    "American Patriot",
    "American patriotism",
    "Confederate Flag",
    "Confederate States Army",
    "Southern Pride",
    "My Big Redneck Family",
    "Redneck Nation",
    "American Civil War",
    "South United"
];
const Hispanic = [];
const lgbtq = [
    "Gay pride", 
    "LGBT community", 
    "Homosexuality", 
    "LGBT culture", 
    "Same-sex marriage", 
    "LGBT United", 
    "Bisexuality", 
    "Gay Rights", 
    "LGBT Equality", 
    "LGBT history", 
    "LGBT rights by country or territory", 
    "LGBT social movements", 
    "Lesbian community", 
    "Rainbow flag (LGBT movement)", 
    "Same-sex marriage in the United States", 
    "Transgenderism"
];
const muslim = [
    "Islam",
    "Islamism",
    "Proud to be A Muslim",
    "Muslim Brotherhood",
    "Jesus in Islam",
    "Quran",
    "Twelver",
    "Hasan ibn Ali",
    "Ali al-Asghar ibn Husayn",
    "Umar",
    "Mecca",
    "Umrah",
    "Muhammad",
    "Muhammad al-Baqir",
    "Ramadan",
    "Abu Bakr",
    "Muhammad al-Mandi",
    "Prophets and messengers in Islam",
    "Ya Hussain",
    "Names of God in Islam",
    "Ahl al-Bayt",
    'KARBALA IMAM HUSSEIN (A.S) SHRINE"',
    "Fard",
    "Ulama",
    "Sunnah Ummah Caliphate",
    "Mufti",
    "Imam",
    "Kaaba",
    "Shia Islam",
    "Abu Talib ibn Abdul-Muttalib",
    "Glossary of Islam",
    "Hadith",
    "Hajj",
    "Zaynab bint Ali",
    "Fiqh",
    "Musa al- Kadhim",
    "Sharia",
    "Sukayna bint Husayn",
    "Mosque",
    "Imam Ali Mosque",
    "Takbir",
    "Hasan al-Askari",
    "Zakat",
    "Shahada",
    "Basmala",
    "Allah",
    "Eid al-Adha",
    "Hijra (Islam)",
    "Prophet",
    "Ali",
    "Fatimah",
    "Ja'far al-Sadiq",
    "Husayn ibn Ali",
    "Abbas ibn Ali",
    "Medina",
    "Sheikh",
    "Sakinah (Fatima al-Kubra) bint Husayn",
    "Ali ibn Husayn Zayn al- Abidin",
    "As-salamu alaykum",
    "Abraham in Islam",
    "Eid al-Fitr",
    "Mary in Islam",
    "Ali al-Ridha",
    "Islam in the United States",
    "Muslim Students' Association",
    "Muslim American Society",
    "Muslim world",
    "Muslim Brotherhood",
    "Muslims Are Not Terrorists",
    "ProductiveMuslim",
    "Muslim Brotherhood",
    "All-american muslim culture",
    "State of Palestine",
    "United Muslims of America"
];
const prisoners = [];
const concervativeGunOwners = [
    "The Second Amendment",
    "Protect the Second Amendment",
    "Preserve our right to keep and bear arms",
    "Gun Rights",
    "Right to keep and bear arms",
    "AR-15",
    "2nd Amendment",
    "Gun Owners of America",
    "Guns & Ammo"
];
const libertarians = [
    "Liberty",
    "Reason (magazine)",
    "Libertarian Party (United States)",
    "Classical liberalism",
    "Libertarianism",
    "Free market",
    "Minarchism",
    "Anarcho-capitalism"
];
const policeForce = [];

module.exports = {
    blackPower,
    antiMuslim,
    whiteNationalist,
    Hispanic,
    lgbtq,
    muslim,
    prisoners,
    concervativeGunOwners,
    libertarians,
    policeForce
}   